In [1]:
import numpy as np

In [5]:
testarr = np.zeros((64,))

In [6]:
np.squeeze(testarr).shape

(64,)

In [8]:
testarr[-1:]

array([0.])

In [11]:
nums = [1, 2, 3, 4, 5, 5]

In [6]:
from collections import Counter
import numpy as np

In [17]:
Counter([3, 1, 3, 1, 2, 2, 4]).values(), Counter([3, 1, 3, 1, 2, 2, 4]).keys()

(dict_values([2, 2, 2, 1]), dict_keys([3, 1, 2, 4]))

In [26]:
votes = None
maxDig = 11
for element, digit in zip(list(Counter([3, 7, 3, 7, 2, 2, 4, 6, 6]).values()), list(Counter([3, 7, 3, 7, 2, 2, 4, 6, 6]).keys())):
    if element == max(list(Counter([3, 1, 3, 1, 2, 2, 4]).values())) and digit < maxDig:
        votes = element 
        maxDig = digit 

In [27]:
maxDig

2

In [9]:
np.argmax(np.bincount([3, 1, 3, 1,  2, 2]))

1

In [10]:
np.bincount([3, 1, 3, 1,  2, 2])

array([0, 2, 2, 2], dtype=int64)

In [45]:
np.argsort([5, 4, 3, 1])

array([3, 2, 1, 0], dtype=int64)

In [3]:
for j in range(0, 7, 2):
    print(j)

0
2
4
6


In [4]:
import torch

c:\Users\altaf\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
torch.randperm(10)[:10]

tensor([5, 0, 2, 6, 1, 9, 4, 8, 7, 3])