In [26]:
import data
import torch
from torch.nn import Module, Linear, ReLU, LogSoftmax, CrossEntropyLoss, Softmax
from torch.optim import SGD, Adam
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics


class MLP(Module):
    """
    Neural Network Classifier
    """

    def __init__(self, input_dim, hidden_dim1, hidden_dim2, output_dim):
        super(MLP, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.hidden_dim1 = hidden_dim1
        self.hidden_dim2 = hidden_dim2

        self.fc1 = Linear(self.input_dim, self.hidden_dim1)
        self.fc2 = Linear(self.hidden_dim1, self.hidden_dim2)
        self.output = Linear(self.hidden_dim2, output_dim)
        self.relu = ReLU()
        self.softmax = Softmax()
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.output(out)
        return out

    def predict(self, x):
        x = torch.FloatTensor(x)
        out = self.forward(x).detach().numpy()
        out = np.where(out == np.max(out), 1, 0)
        return out 

def test(net, X_train, y_train, X_test, y_test):

    test_out = np.argmax(net(torch.FloatTensor(X_test)).detach().numpy(), 1)
    train_out = np.argmax(net(torch.FloatTensor(X_train)).detach().numpy(), 1)

    test_accuracy = np.sum(np.where(test_out == y_test, 1, 0))/y_test.shape[0]
    train_accuracy = np.sum(np.where(train_out == y_train, 1, 0))/y_train.shape[0]

    acc1 = metrics.accuracy_score(y_pred=test_out, y_true=y_test)
    acc2 = metrics.accuracy_score(y_pred=train_out, y_true=y_train)

    print('Test accuracy: ' + str(acc1))
    print('Train accuracy: ' + str(acc2))

def train(net, X_train, y_train, X_test, y_test, batch_size=10, epochs=200, lr=0.001):

    X_train = torch.FloatTensor(X_train)
    y_train = torch.LongTensor(y_train)

    criterion = CrossEntropyLoss()
    optimizer = Adam(net.parameters(), lr=lr, weight_decay=5e-8)

    for i in range(epochs):

        print(i)

        batch_loss = 0
        randShuffle = torch.randperm(X_train.size()[0])
        X_train_shuff = X_train[randShuffle]
        y_train_shuff = y_train[randShuffle]        

        for j in range(0, X_train.size()[0], batch_size):

            X_batch = X_train_shuff[j:j+batch_size]
            y_batch = y_train_shuff[j:j+batch_size]

            optimizer.zero_grad()

            out = net(X_batch)

            loss = criterion(out.squeeze(), y_batch)   

            batch_loss += loss   
            
            loss.backward()
            optimizer.step()

        print(batch_loss)

    return net

def main():

    train_data, train_labels, test_data, test_labels = data.load_all_data('data')

    num_classes = 10
    net = MLP(64, 16, 16, num_classes)
    model = train(net, X_train=train_data, y_train=train_labels, X_test=test_data, y_test=test_labels)

    test(model, train_data, train_labels, test_data, test_labels)

    return net 

if __name__ == '__main__':
    net = main()


0
tensor(939.3317, grad_fn=<AddBackward0>)
1
tensor(321.6891, grad_fn=<AddBackward0>)
2
tensor(243.9262, grad_fn=<AddBackward0>)
3
tensor(215.7514, grad_fn=<AddBackward0>)
4
tensor(199.4989, grad_fn=<AddBackward0>)
5
tensor(188.8028, grad_fn=<AddBackward0>)
6
tensor(179.1770, grad_fn=<AddBackward0>)
7
tensor(172.3307, grad_fn=<AddBackward0>)
8
tensor(164.4504, grad_fn=<AddBackward0>)
9
tensor(158.9123, grad_fn=<AddBackward0>)
10
tensor(150.8862, grad_fn=<AddBackward0>)
11
tensor(143.4997, grad_fn=<AddBackward0>)
12
tensor(137.4288, grad_fn=<AddBackward0>)
13
tensor(130.8406, grad_fn=<AddBackward0>)
14
tensor(124.9614, grad_fn=<AddBackward0>)
15
tensor(121.3788, grad_fn=<AddBackward0>)
16
tensor(117.3499, grad_fn=<AddBackward0>)
17
tensor(114.5565, grad_fn=<AddBackward0>)
18
tensor(109.8407, grad_fn=<AddBackward0>)
19
tensor(107.4858, grad_fn=<AddBackward0>)
20
tensor(105.6412, grad_fn=<AddBackward0>)
21
tensor(102.5604, grad_fn=<AddBackward0>)
22
tensor(100.1345, grad_fn=<AddBackward0>

In [27]:
train_data, train_labels, test_data, test_labels = data.load_all_data('data')


In [28]:
torch.FloatTensor(test_data[0])

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0200, 0.8500, 0.5400, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.6200, 0.9900, 0.3800, 0.0000, 0.0000,
        0.0000, 0.0000, 0.2200, 0.9500, 0.5700, 0.0000, 0.0000, 0.0000, 0.0000,
        0.3500, 0.9400, 0.4500, 0.0100, 0.0000, 0.0000, 0.0000, 0.4400, 0.9400,
        0.3200, 0.0000, 0.0000, 0.0000, 0.0000, 0.5400, 0.8900, 0.1800, 0.0000,
        0.0000, 0.0000, 0.0000, 0.4400, 0.9600, 0.2100, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.4200, 0.8000, 0.3600, 0.0300, 0.0000, 0.0000, 0.0000,
        0.0000])

In [29]:
net.predict(torch.FloatTensor(test_data[0]))

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
test_labels[0]

1.0

In [6]:
from collections import Counter
import numpy as np

In [17]:
Counter([3, 1, 3, 1, 2, 2, 4]).values(), Counter([3, 1, 3, 1, 2, 2, 4]).keys()

(dict_values([2, 2, 2, 1]), dict_keys([3, 1, 2, 4]))

In [26]:
votes = None
maxDig = 11
for element, digit in zip(list(Counter([3, 7, 3, 7, 2, 2, 4, 6, 6]).values()), list(Counter([3, 7, 3, 7, 2, 2, 4, 6, 6]).keys())):
    if element == max(list(Counter([3, 1, 3, 1, 2, 2, 4]).values())) and digit < maxDig:
        votes = element 
        maxDig = digit 

In [27]:
maxDig

2

In [9]:
np.argmax(np.bincount([3, 1, 3, 1,  2, 2]))

1

In [10]:
np.bincount([3, 1, 3, 1,  2, 2])

array([0, 2, 2, 2], dtype=int64)

In [45]:
np.argsort([5, 4, 3, 1])

array([3, 2, 1, 0], dtype=int64)

In [3]:
for j in range(0, 7, 2):
    print(j)

0
2
4
6


In [4]:
import torch

c:\Users\altaf\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
torch.randperm(10)[:10]

tensor([5, 0, 2, 6, 1, 9, 4, 8, 7, 3])